"""clean migration

Revision ID: e8907e5318dc
Revises: 8a26332e5530
Create Date: 2026-06-19 15:01:30.465618

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8907e5318dc"
down_revision: Union[str, Sequence[str], None] = "8a26332e5530"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("company_code", sa.String(), nullable=False))
    op.add_column("companies", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_companies_company_code"), "companies", ["company_code"], unique=True
    )
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_company_code"), table_name="companies")
    op.drop_column("companies", "updated_at")
    op.drop_column("companies", "company_code")
    # ### end Alembic commands ###
