"""Alert model definitions."""

import enum
from datetime import datetime

from sqlalchemy import Column, DateTime, Enum, ForeignKey, Integer, String

from app.db import Base


class AlertType(enum.Enum):
    """Types of alerts generated by the fleet system."""

    GEOFENCE = "geofence"
    OVERHEATING = "overheating"
    OVERSPEED = "overspeed"


class Alert(Base):
    """Model for storing generated alerts."""

    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True)
    vehicle_id = Column(Integer, ForeignKey("vehicles.id"))
    company_id = Column(Integer, ForeignKey("companies.id"))
    alert_type = Column(Enum(AlertType))
    message = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)
